"""
Pipeline debugger — runs the ADK pipeline directly (no queue)
so we can see exactly which agent fails and why.

Run from ripple-backend-local folder:
    python debug_pipeline.py
"""

import sys, asyncio, json, traceback
sys.path.insert(0, ".")

# ── Step 1: Check DB has data ─────────────────────────────────────────────────
print("\n[1] Checking database...")
from app.services.database import Database
Database.init()
stats = Database.stats()
print(f"    DB stats: {stats}")

events = Database.list_active_events(limit=1)
if not events:
    print("    No active events found — create one first via test_pipeline.py")
    sys.exit(1)

event = events[0]
print(f"    Using event: {event['id'][:8]}... supplier={event['supplier_id'][:8]}...")

# ── Step 2: Test ML client directly ──────────────────────────────────────────
print("\n[2] Testing ML client (calling port 8081)...")
import asyncio

async def test_ml():
    from app.services.ml_client import MLClient
    client = MLClient()

    reachable = await client.is_reachable()
    print(f"    ML reachable: {reachable}")
    if not reachable:
        print("    ERROR: ML server not running on port 8081")
        return None

    try:
        result = await client.predict(event)
        preds = result.get("predictions", {})
        print(f"    Predictions received: {len(preds)} nodes")
        print(f"    Model version: {result.get('model_version')}")
        print(f"    Inference ms: {result.get('inference_ms')}")

        # Show top 3 risk scores
        sorted_preds = sorted(preds.items(),
                              key=lambda x: x[1].get("peak_risk_score", 0),
                              reverse=True)[:3]
        print("    Top 3 risk scores:")
        for sid, pred in sorted_preds:
            print(f"      {sid[:8]}... peak={pred.get('peak_risk_score'):.3f} "
                  f"level={pred.get('risk_level')}")
        return result
    except Exception as e:
        print(f"    ERROR calling ML: {e}")
        traceback.print_exc()
        return None

ml_result = asyncio.run(test_ml())

# ── Step 3: Run MonitorAgent ──────────────────────────────────────────────────
print("\n[3] Running MonitorAgent...")
async def test_monitor():
    from app.agents.pipeline import MonitorAgent
    agent = MonitorAgent()
    try:
        out = await agent.process(event)
        print(f"    OK — enriched={out['enriched']}")
        return out
    except Exception as e:
        print(f"    ERROR: {e}")
        traceback.print_exc()
        return None

monitor_out = asyncio.run(test_monitor())

# ── Step 4: Run AnalystAgent ──────────────────────────────────────────────────
print("\n[4] Running AnalystAgent...")
async def test_analyst():
    from app.agents.pipeline import AnalystAgent
    agent = AnalystAgent()
    try:
        out = await agent.analyze(monitor_out)
        print(f"    OK — predictions={len(out['predictions'])} nodes")
        print(f"    Peak risk: {out['peak_risk']:.3f}")
        print(f"    Critical:  {out['critical_count']}")
        print(f"    Revenue:   ${out['revenue_at_risk']/1e9:.2f}B")
        print(f"    Model:     {out['model_version']}")
        return out
    except Exception as e:
        print(f"    ERROR: {e}")
        traceback.print_exc()
        return None

analyst_out = asyncio.run(test_analyst()) if monitor_out else None

# ── Step 5: Run RecommenderAgent ─────────────────────────────────────────────
print("\n[5] Running RecommenderAgent...")
async def test_recommender():
    from app.agents.pipeline import RecommenderAgent
    agent = RecommenderAgent()
    try:
        out = await agent.recommend(analyst_out)
        print(f"    OK — urgency={out['urgency']}")
        print(f"    Generated by: {out['generated_by']}")
        print(f"    Recommendations: {len(out['recommendations'])}")
        for r in out["recommendations"][:2]:
            print(f"      [{r.get('rank')}] {r.get('action','')[:60]}")
        return out
    except Exception as e:
        print(f"    ERROR: {e}")
        traceback.print_exc()
        return None

rec_out = asyncio.run(test_recommender()) if analyst_out else None

# ── Step 6: Save prediction to DB ─────────────────────────────────────────────
print("\n[6] Saving prediction to DB...")
if analyst_out and rec_out:
    import uuid
    from datetime import datetime
    rec_list = [r.get("action","") for r in rec_out.get("recommendations",[])]
    pred = {
        "id":                       str(uuid.uuid4()),
        "trigger_event_id":         event["id"],
        "supplier_id":              event["supplier_id"],
        "peak_risk_score":          round(analyst_out["peak_risk"], 4),
        "peak_risk_day":            7,
        "risk_level":               "critical" if analyst_out["peak_risk"]>0.7 else "high",
        "confidence":               0.85,
        "total_revenue_at_risk_usd":round(analyst_out["revenue_at_risk"], 2),
        "affected_supplier_count":  analyst_out["affected_count"],
        "critical_count":           analyst_out["critical_count"],
        "high_count":               analyst_out["high_count"],
        "model_version":            analyst_out["model_version"],
        "recommendations":          json.dumps(rec_list),
        "urgency":                  rec_out["urgency"],
    }
    try:
        Database.save_prediction(pred)
        print(f"    OK — prediction saved")
        print(f"    Revenue at risk: ${pred['total_revenue_at_risk_usd']/1e9:.2f}B")
        print(f"    Urgency: {pred['urgency']}")

        # Verify it's in DB
        summary = Database.get_risk_summary()
        print(f"\n    DB summary after save:")
        print(f"      revenue_at_risk: ${float(summary.get('total_revenue_at_risk_usd',0))/1e9:.2f}B")
        print(f"      affected:        {summary.get('affected_suppliers')}")
    except Exception as e:
        print(f"    ERROR saving: {e}")
        traceback.print_exc()
else:
    print("    Skipped — earlier agent failed")

print("\n" + "="*55)
print("  Debug complete. Paste full output to Claude.")
print("="*55)
